### ISSUE TITLE
User agent

### ISSUE THREAD

**Issue by Comarco** [millette/verra#12]
Pitêtre qu'un user agent moins remarquable serait plusse mieux :P

**Comment by millette** [comment]
Je pourrais mettre une option "incognito" ou quelque chose comme ça pour utiliser un user-agent très ordinaire (mozilla...)

**Comment by ubik23** [comment]
Ça pourrait même être le default.

**Comment by millette** [comment]
Faudrait m'expliquer vos raisons pour que incognito soit par défaut.
